App_Survey/urls.py
from django.urls import path, include
from . import views

app_name = 'App_Survey'

urlpatterns = [
    path('', views.home, name='home'),
    path('submit_complain/', views.submit_complain, name='submit_complain'),
    path('submit_feedback/', views.submit_suggestion, name='submit_suggestion'),
    path('resolve-complain/<int:complain_id>/', views.resolve_complain, name='resolve_complain'),
    path('search-resolved/', views.search_resolved_complain, name='search_resolved_complain'),
    path('submission-complete/', views.submission_complete, name='submission_complete'),
    # path('survey/admin/', views.signin_user, name='signin'),
    path('admin-login/', views.admin_login_view, name='admin_login'),
    path('dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('signout/', views.signout_user, name='signout'),
    path('complains/', views.complaint_list, name='complaint_list'),
    path('feedbacks/', views.suggestion_list, name='suggestion_list'),
    path('complaints/edit/<int:complain_id>/', views.edit_complain, name='edit_complain'),
    path('resolved/', views.resolved_feedback_list, name='resolved'),
    path('complain/<int:pk>/details/', views.complain_details, name='complain_details'),

    path('createuser/', views.register_user_profile, name='register_profile'),
    path('profile/<int:user_id>/', views.view_profile, name='view_profile'),
    path('profile/update/<int:user_id>/', views.update_profile, name='update_profile'),
    path('userprofiles/', views.user_profile_list, name='user_profile_list'),
    path('complaints/export/csv/', views.export_complaints_csv, name='export_complaints_csv'),
    path('feedbacks/export/csv/', views.export_feedback_csv, name='export_feedback_csv'),
    path('solutions/export/csv/', views.export_solution_csv, name='export_solution_csv'),
    path('complaints/export/pdf/', views.export_complaints_pdf, name='export_complaints_pdf'),
    # path('accounts/', include('allauth.urls')),
    
]

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Survey.urls')),
    # path('api/admin_panel/', include('admin_panel.urls')),
    # path('oauth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Survey/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
import re

class UserProfileManager(BaseUserManager):
    """Manager for user profiles"""

    def create_user(self, email, name, password=None):
        """Create a new user profile"""
        if not email:
            raise ValueError('User must have an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, name=name)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, name, password):
        """Create and save a superuser"""
        user = self.create_user(email, name, password)

        user.is_superuser = True
        user.is_staff = False
        user.save(using=self._db)

        return user

class UserProfile(AbstractBaseUser, PermissionsMixin):
    """Database model for users in the system"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserProfileManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        """Retrieve full name of the user"""
        return self.name

    def get_short_name(self):
        """Retrieve short name of the user"""
        return self.name

    def __str__(self):
        """Return string representation of our user"""
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=100, blank=True)
    address1 = models.TextField(max_length=400, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    joined_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.email + "'s Profile"

    # Check if all fields in the profile are filled
    def is_fully_filled(self):
        fields_name = [f.name for f in self._meta.get_fields()]

        for field_name in fields_name:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True

# Signal to create or update profile when user is created
# @receiver(post_save, sender=UserProfile)
# def create_or_update_user_profile(sender, instance, created, **kwargs):
#     print(instance)
#     if created:
#         Profile.objects.create(user=instance)     
#     else:
#         instance.profile.save()

@receiver(post_save, sender=UserProfile)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    Profile.objects.get_or_create(user=instance)  


# Custom validator for student ID
def validate_student_id(value):
    if not re.match(r'^\d{8}$', value):  
        raise ValidationError("Student ID must be exactly 8 digits.")
    if value == "12345678":
        raise ValidationError("Student ID cannot be a serial number like 12345678.")

class Complain(models.Model):
    class FeedbackStatus(models.TextChoices):
        PENDING = 'Pending', 'Pending'
        SOLVED = 'Solved', 'Solved'
        ON_PROCESS = 'On Process', 'On Process'

    class CategoryStatus(models.TextChoices):
        # NONE = 'None', 'None'
        FOREIGN_MATERIAL = 'Foreign Material', 'Foreign Material'
        PERSONAL_HYGIENE = 'Personal Hygiene', 'Personal Hygiene'
        FOOD_QUALITY = 'Food Quality', 'Food Quality'
        OTHERS = 'Others', 'Others'

    student_name = models.CharField(max_length=100, blank=True, null=True)
    student_id = models.CharField(max_length=8, validators=[validate_student_id])
    category = models.CharField(max_length=20, choices=CategoryStatus.choices, null=True)
    problem_details = models.TextField()
    complain_image = models.ImageField(upload_to='complain_images/', blank=True, null=True)
    is_resolved = models.BooleanField(default=False)
    is_valid = models.BooleanField(default=False)
    is_feedback = models.BooleanField(default=False) 
    invoice_no = models.CharField(max_length=20, blank=True, null=True)
    invoice_image = models.ImageField(upload_to='invoice_images/', blank=True, null=True)
    resolved_image = models.ImageField(upload_to='resolved_images/', blank=True, null=True)
    solution_details = models.TextField(blank=True, null=True, default="Pending")
    feedback_status = models.CharField(max_length=10, choices=FeedbackStatus.choices, default=FeedbackStatus.PENDING)
    submitted_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"{self.student_name} - {self.student_id}"
    
    def save(self, *args, **kwargs):
        if self.feedback_status == self.FeedbackStatus.SOLVED:
            self.is_resolved = True
        else:
            self.is_resolved = False
        super().save(*args, **kwargs)

App_Survey/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from .models import Complain, Profile, UserProfile
from .forms import ComplainForm, ResolveForm, FeedbackForm
from django.contrib.admin.views.decorators import staff_member_required
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib import messages
from .forms import AdminLoginForm, UserProfileCreationForm, ProfileForm
from django.urls import reverse 
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.db.models import Q
from datetime import datetime
from django.core.mail import send_mail
from django.conf import settings
import csv
from django.http import HttpResponse
from django.db.models import Count
import openpyxl
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from openpyxl import Workbook
from Core.settings import DEFAULT_FROM_EMAIL


def home(request):
    return render(request, 'students/home.html')

def submit_complain(request):
    if request.method == 'POST':
        form = ComplainForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the form
            complain = form.save(commit=False)
            complain.is_feedback = False
            complain.save()

            # try:
            # subject = f"New Feedback From Khabardabar Catering is Submitted by {complain.student_id}"
            # message = f"Name: {complain.student_name}\n" \
            #         f"ID: {complain.student_id}\n" \
            #         f"Complain Category : {complain.category}\n" \
            #         f"Invoice Number: {complain.invoice_no}\n" \
            #         f"Feedback Details: {complain.problem_details}\n"                              
            # recipients = ['testnetworkeverything@gmail.com','shovonmufrid98@gmail.com']
            
            # # Send email
            # send_mail(
            #     subject,
            #     message,
            #     DEFAULT_FROM_EMAIL,
            #     recipients,
            #     fail_silently=False
            # )
            # except:
            #     pass

            return JsonResponse({'redirect_url': reverse('App_Survey:submission_complete')})
        else:
            return JsonResponse({'errors': form.errors}, status=400)
    
    form = ComplainForm()
    return render(request, 'students/feedback.html', {'form': form})

def submit_suggestion(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.is_feedback = True
            suggestion.save()
            return JsonResponse({'redirect_url': reverse('App_Survey:submission_complete')})
        else:
            return JsonResponse({'errors': form.errors}, status=400)
    
    form = FeedbackForm()
    return render(request, 'students/suggestion.html', {'form': form})


# For admins to resolve complaints
@staff_member_required
def resolve_complain(request, complain_id):
    complain = get_object_or_404(Complain, id=complain_id)
    if request.method == 'POST':
        form = ResolveForm(request.POST, request.FILES, instance=complain)
        if form.is_valid():
            complain.is_resolved = True
            form.save()
            return redirect('App_Survey:admin_complain_list')
    else:
        form = ResolveForm(instance=complain)
    return render(request, 'students/resolve_complain.html', {'form': form, 'complain': complain})

def search_resolved_complain(request):
    student_id = request.GET.get('student_id', '')
    complaints = Complain.objects.filter(student_id=student_id) if student_id else []
    return render(request, 'students/resolved_complaints.html', {'complaints': complaints, 'student_id': student_id})


def submission_complete(request):
    return render(request, 'students/submission_complete.html')



def is_admin(user):
    return user.is_staff

def admin_login_view(request):
    if request.user.is_authenticated and request.user.is_staff:
        return redirect('App_Survey:admin_dashboard')  

    if request.method == 'POST':
        form = AdminLoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=email, password=password)
            
            if user is not None and user.is_staff: 
                login(request, user)
                return redirect('App_Survey:admin_dashboard')  
            else:
                messages.error(request, "Invalid credentials or you are not authorized.")
        else:
            messages.error(request, "Invalid form submission.")
    else:
        form = AdminLoginForm()

    return render(request, 'App_Survey/signin.html', {'form': form})


@user_passes_test(is_admin) 
def admin_dashboard_view(request):
    total_active_profiles = Profile.objects.filter(user__is_active=True).count()
    total_resolved_complaints = Complain.objects.filter(is_resolved=True).count()
    total_unresolved_complaints = Complain.objects.filter(is_resolved=False).count()
    total_complain = Complain.objects.filter(is_feedback=False).count()
    total_feedback = Complain.objects.filter(is_feedback=True).count()
    total_complaints = total_complain + total_feedback
    current_user_email = request.user.email

    category_status_counts = {
        'Foreign_Material': 0,
        'Personal_Hygiene': 0,
        'Food_Quality': 0,
        'Others': 0
    }
    category_counts = Complain.objects.values('category').annotate(count=Count('category'))

    for category in category_counts:
        category_name = category['category']
        if category_name:  # Check if category is not None
            category_name = category_name.replace(' ', '_')
            if category_name in category_status_counts:
                category_status_counts[category_name] = category['count']


    context = {
        'total_active_profiles': total_active_profiles,
        'total_resolved_complaints': total_resolved_complaints,
        'total_unresolved_complaints': total_unresolved_complaints,
        'total_complaints': total_complaints,
        'current_user_email': current_user_email,  
        'category_status_counts': category_status_counts,
        'total_complain': total_complain,
        'total_feedback': total_feedback,

    }

    return render(request, 'App_Survey/dashboard.html', context)

@login_required
def signout_user(request):
     logout(request)
     messages.warning(request, "You are Logged Out")
     return HttpResponseRedirect(reverse('App_Survey:admin_login'))


@staff_member_required
def complaint_list(request):
    complaints = Complain.objects.filter(is_feedback=False).order_by('-id')

    # Get filter inputs
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    student_id = request.GET.get('student_id')
    category = request.GET.get('category') 

    # Filter by date range
    if start_date and end_date:
        try:
            start_date = datetime.strptime(start_date, '%Y-%m-%d')
            end_date = datetime.strptime(end_date, '%Y-%m-%d')
            complaints = complaints.filter(submitted_at__date__range=[start_date, end_date])
        except ValueError:
            pass 

    # Filter by student_id
    if student_id:
        complaints = complaints.filter(student_id__icontains=student_id)

    # Filter by category
    # if category and category != "None":
    if category:
        complaints = complaints.filter(category=category)

    # Pagination
    paginator = Paginator(complaints, 10) 
    page_number = request.GET.get('page')
    complaints = paginator.get_page(page_number)
    categories = Complain.CategoryStatus.choices 
    return render(request, 'App_Survey/complaint_list.html', {'complaints': complaints, 'categories': categories})

@staff_member_required
def suggestion_list(request):
    suggestions = Complain.objects.filter(is_feedback=True).order_by('-id')
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    student_id = request.GET.get('student_id')

    # Date range filter
    if start_date and end_date:
        try:
            start_date = datetime.strptime(start_date, '%Y-%m-%d')
            end_date = datetime.strptime(end_date, '%Y-%m-%d')
            suggestions = suggestions.filter(submitted_at__date__range=[start_date, end_date])
        except ValueError:
            pass 

    # Student ID filter
    if student_id:
        suggestions = suggestions.filter(student_id__icontains=student_id)

    # Pagination
    paginator = Paginator(suggestions, 10)
    page_number = request.GET.get('page')
    suggestions = paginator.get_page(page_number)

    categories = Complain.CategoryStatus.choices
    return render(request, 'App_Survey/feedback_list.html', {'complaints': suggestions,})

@staff_member_required
def edit_complain(request, complain_id):
    complain = get_object_or_404(Complain, id=complain_id)
    if request.method == 'POST':
        form = ResolveForm(request.POST, request.FILES, instance=complain)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True}) 
    else:
        form = ResolveForm(instance=complain)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        html = render_to_string('App_Survey/complain_edit_modal.html', {'form': form, 'complain': complain}, request=request)
        return JsonResponse({'html': html}) 

templates/App_Survey/complain_edit.html
{% extends 'layouts/base.html' %}

{% block body_block %}
<h2>Update Feedback With Solution</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save Changes</button>
    <a href="{% url 'App_Survey:complaint_list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

templates/App_Survey/complaint_list.html
{% extends 'layouts/base.html' %} 
{% block span_block %} 
All Feedbacks 
{% endblock span_block %} 

{% block body_block %}

    <div class="card card-default">
      <div class="card-header">
        <h2>All Complain Table</h2>
      </div>
      <div class="card-body">
        <form method="GET" id="filter-form" action="{% url 'App_Survey:complaint_list' %}">
          <div class="row mb-3">
              <div class="col-md-2">
                <label for="student-id">Student ID:</label>
              <input type="text" class="form-control" id="student-id" name="student_id" placeholder="Search by Student ID" value="{{ request.GET.student_id }}">
              </div>
              <div class="col-md-2">
                <label for="category">Category:</label>
                <select class="form-control" id="category" name="category">
                  <option value="" {% if not request.GET.category %}selected{% endif %}>All Categories</option>
                  {% for value, label in categories %}
                      <option value="{{ value }}" {% if request.GET.category == value %}selected{% endif %}>{{ label }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-2">
                  <label for="start-date">Start Date:</label>
                  <input type="date" class="form-control" id="start-date" name="start_date" value="{{ request.GET.start_date }}">
              </div>
              <div class="col-md-2">
                  <label for="end-date">End Date:</label>
                  <input type="date" class="form-control" id="end-date" name="end_date" value="{{ request.GET.end_date }}">
              </div>
              <div class="col-md-1">
                <h3 style="color: white">.</h3>
                <button type="submit" class="btn btn-primary btn-sm">Search</button>
              </div>
              <div class="col-md-1">
                <h3 style="color: white">.</h3>
                <a href="{% url 'App_Survey:complaint_list' %}" class="btn btn-secondary btn-sm">X</a>
              </div>
              <div class="col-md-2">
                <h3 style="color: white">.</h3>
                <a href="{% url 'App_Survey:export_complaints_csv' %}?start_date={{ request.GET.start_date }}&end_date={{ request.GET.end_date }}" class="btn btn-success btn-sm">CSV Download</a>

              </div>
          </div>
        </form>
      
        <div class="collapse" id="collapse-data-tables">
          <pre class="language-html mb-4"></pre>
        </div>
        <table
          id="productsTable"
          class="table table-hover table-product"
          style="width: 100%"
        >
          <thead>
            <tr>
                <th>SL</th>
                <th>ID</th>
                <!-- <th>Name</th> -->
                <th>Feedback</th>
                <th>Category</th>
                <!-- <th>Feedback</th> -->
                <th>Inv. Image</th>
                <th>Complain Image</th>
                <th>Status</th>
                <th>Issued</th>
                {% if request.user.is_superuser %}
                  <th>View</th>
                  <th>Action</th>
                {% endif %}
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for complain in complaints %}
            <tr id="complain-row-{{ complain.id }}">
                <td>{{ forloop.counter }}</td>
                <td>{{ complain.student_id }}</td>
                <td>{{ complain.is_feedback }}</td>
                <td>{{ complain.category }}</td>
                <!-- <td  style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ complain.problem_details | truncatechars:10  }}</td> -->
                <td style="text-align: center;">
                    {% if complain.invoice_image %}
                        <span class="mdi mdi-image-multiple large" style="cursor: pointer;" onclick="viewImage('{{ complain.invoice_image.url }}')" ></span>
                    {% else %}
                        No image
                    {% endif %}
                </td>
                <td style="text-align: center;">
                    {% if complain.complain_image %}
                        <span class="mdi mdi-image-multiple large" style="cursor: pointer;" onclick="viewImage('{{ complain.complain_image.url }}')" ></span>
                    {% else %}
                        No image
                    {% endif %}
                </td>
                <td style="text-align: center; color:
                            {% if complain.feedback_status == 'Pending' %}
                                red
                            {% elif complain.feedback_status == 'Solved' %}
                                green
                            {% elif complain.feedback_status == 'On Process' %}
                                blue
                            {% endif %}
                            ">
                            {{ complain.feedback_status }}
                            </td>
                <td>{{ complain.submitted_at }}</td>
                {% if request.user.is_superuser %}
                  <td>
                    <button
                      type="button"
                      class="btn btn-info btn-pill btn-sm"
                      data-toggle="modal"
                      data-target="#exampleModalForm"
                      onclick="viewComplainDetails(
                          '{{ complain.student_name }}', 
                          '{{ complain.student_id }}', 
                          '{{ complain.problem_details }}', 
                          '{{ complain.invoice_no }}', 
                          {% if complain.invoice_image %}'{{ complain.invoice_image.url }}'{% else %}null{% endif %}, 
                          {% if complain.complain_image %}'{{ complain.complain_image.url }}'{% else %}null{% endif %}, 
                          '{{ complain.submitted_at }}', 
                          '{{ complain.feedback_status }}')">
                      View
                    </button>
                  </td>
                  <td>
                    <a href="#" class="btn btn-primary btn-sm btn-pill" data-toggle="modal" data-target="#editModal"
                      onclick="openEditModal({{ complain.id }})">Solve</a>
                  </td>
                {% endif %}
                  <!-- <td></td> -->
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      
      <!-- ================= Pagination ================ -->
      <div class="card card-default align-items-end">
        <div class="card-body">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                {% if complaints.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ complaints.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true" class="mdi mdi-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                    </a>
                </li>
                {% endif %}

                {% for i in complaints.paginator.page_range %}
                    {% if complaints.number == i %}
                        <li class="page-item active"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if complaints.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ complaints.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true" class="mdi mdi-chevron-right"></span>
                    <span class="sr-only">Next</span>
                    </a>
                </li>
                {% endif %}
                </ul>
            </nav>
        </div>
    </div>
  </div>

<!--============== View Modal ==============-->
<div class="modal fade" id="exampleModalForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalFormTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalFormTitle">Feedback Details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <p><strong>Student Name:</strong> <span id="modalStudentName"></span></p>
        <p><strong>Student ID:</strong> <span id="modalStudentID"></span></p>
        <p><strong>Problem Details:</strong> <span id="modalProblemDetails"></span></p>
        <p><strong>Invoice No.:</strong> <span id="modalInvoiceNo"></span></p>
        <p><strong>Invoice Image:</strong> 
          <img id="modalInvoiceImage" src="" alt="Invoice Image" style="max-width: 100%; display: none;">
          <span id="modalInvoiceImagePlaceholder"></span>
        </p>
        <br>
        <p><strong>Complaint Image:</strong> 
          <img id="modalComplainImage" src="" alt="Complain Image" style="max-width: 100%; display: none;">
          <span id="modalComplainImagePlaceholder"></span>
        </p>
        <br>
        <p><strong>Submitted At:</strong> <span id="modalSubmittedAt"></span></p>
        <p><strong>Feedback Status:</strong> <span id="modalFeedbackStatus"></span></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-pill" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!--=================== Image Open =============================-->
<div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="imageModalLabel">Feedback Image</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="modalImage" src="" alt="Complaint Image" class="img-fluid" />
            </div>
        </div>
    </div>
</div>

<!-- ========= Edit Modal =========== -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Update Feedback With Solution</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modalEditForm">
      </div>
    </div>
  </div>
</div>

<script>
    function viewImage(imageUrl) {
        document.getElementById('modalImage').src = imageUrl;
        $('#imageModal').modal('show');
    }
    function openEditModal(complainId) {
      $.ajax({
          url: "{% url 'App_Survey:edit_complain' 0 %}".replace(0, complainId),
          type: "GET",
          success: function(response) {
              $('#modalEditForm').html(response.html); 
              $('#editModal').modal('show'); 
          },
          error: function(xhr, status, error) {
              console.log("Error loading modal:", error);
          }
      });
  }

    // View Modal
    function viewComplainDetails(student_name, student_id, problem_details, invoice_no, invoice_image, complain_image, submitted_at, feedback_status) {
    document.getElementById('modalStudentName').textContent = student_name;
    document.getElementById('modalStudentID').textContent = student_id;
    document.getElementById('modalProblemDetails').textContent = problem_details;
    document.getElementById('modalInvoiceNo').textContent = invoice_no;
    
    const modalInvoiceImage = document.getElementById('modalInvoiceImage');
    if (invoice_image && invoice_image !== "None") {
      modalInvoiceImage.src = invoice_image;
      modalInvoiceImage.style.display = "block"; 
    } else {
      modalInvoiceImage.style.display = "none"; 
      document.getElementById('modalInvoiceImagePlaceholder').textContent = "No Image Available";
    }

    const modalComplainImage = document.getElementById('modalComplainImage');
    if (complain_image && complain_image !== "None") {
      modalComplainImage.src = complain_image;
      modalComplainImage.style.display = "block"; 
    } else {
      modalComplainImage.style.display = "none"; 
      document.getElementById('modalComplainImagePlaceholder').textContent = "No Image Available";
    }

    document.getElementById('modalSubmittedAt').textContent = submitted_at;
    document.getElementById('modalFeedbackStatus').textContent = feedback_status;
  }


</script>

{% endblock %} 